### ISSUE TITLE
DGMR Model Download and Crop Size

### ISSUE THREAD

**Issue by p3jitnath** [MeteoSwiss/ldcast#3]
To test DeepMind's DGMR I did try to run the colab notebook (https://github.com/deepmind/deepmind-research/blob/master/nowcasting/Open_sourced_dataset_and_model_snapshot_for_precipitation_nowcasting.ipynb), and extracting the model from tfhub but it seems it is being served by a GCP Storage Bucket (which I presume will require gsutil but can't seem to get a hold of the endpoint). 

For your own evaluations, can you guide on how did you go about downloading the DGMR model and also which crop size did you use (eg. 256x256)?

**Comment by jleinonen** [comment]
Yes, the 256x256 model size is used for evaluation.

If you don't want to deal with gsutil it's also possible to download the DGMR model files from the Google Cloud Storage web interface: https://console.cloud.google.com/storage/browser/dm-nowcasting-example-data/tfhub_snapshots. The web interface only allows you to download individual files but since there are only around 10 of them in the model snapshot it's feasible to get the model also that way.
